# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  # vagrant plugin install vagrant-disksize
  config.disksize.size = "50GB"
  config.vm.synced_folder "../data", "/data", create: true, owner: "root", group: "root", mount_options: ["dmode=755","fmode=755"]
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 2048
     vb.cpus   = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
      sh /data/base.sh
      sh /data/docker.sh
  SHELL
  (1..1).each do |i|
    config.vm.define "master#{i}" do |master|
      master.vm.hostname = "master#{i}"
      master.vm.network "private_network",ip:"172.16.3.24#{i}",auto_config: true
      master.vm.provider "virtualbox" do |vb|
         vb.name = "master#{i}"
      end
    end
  end
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.network "private_network",ip:"172.16.3.25#{i}",auto_config: true
      node.vm.provider "virtualbox" do |vb|
         vb.name = "node#{i}"
      end
    end
  end
end